version: '3'
services:
  pgsql-db:
    image: postgres:14.4
    restart: always
    container_name: pgsql-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sdkjdf13
      - POSTGRES_DB=stepsharp
      - TZ= Australia/Sydney
    ports:
      - 5436:5432
    volumes:
      - ./pgsql:/var/lib/postgresql/data
#    network_mode: "host"
    networks:
      - app-network
      
  web-app-deapvision:
    build:
      context: ./
      dockerfile: Dockerfile
    image: web-app-deapvision
    restart: always
    container_name: web-app-deapvision
    ports:
      - '4000:3000'
    depends_on:
      - pgsql-db
    volumes:
      -  .env.local:/app/.env.local # any change to base folder should be reflected
    networks:
      - app-network
      
  pgadmin:
    image: dpage/pgadmin4:6.12
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: stepsharp@gmail.com
      PGADMIN_DEFAULT_PASSWORD: stepsharp24
      PGADMIN_LISTEN_PORT: 5050
      TZ: Australia/Sydney
    ports:
     - "5050:5050"
    depends_on:
      - pgsql-db
    volumes:
      - ./pgadmin:/var/lib/pgadmin

    networks:
      - app-network
      
 #Docker Networks
# docker network create app-network (create command for network)
networks:
  app-network:
    driver: bridge
    external: true
#Volumes
volumes:
  dbdata:
    driver: local
